# Generated by Django 5.0.1 on 2024-01-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='pin',
        ),
    ]
