# Generated by Django 5.0.1 on 2024-01-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pins',
            old_name='descrliption',
            new_name='description',
        ),
    ]
