# Generated by Django 5.0.1 on 2024-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pins', '0004_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='updated_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
