# Generated by Django 5.0.1 on 2024-01-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_remove_user_name_user_country_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('KR', 'Korea')], default=None, max_length=10, null=True, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('KR', 'Korean')], default=None, max_length=10, null=True, verbose_name='언어'),
        ),
    ]
